#+TITLE:     React-Native Android
#+AUTHOR:    Jongseok Choi
#+EMAIL:     hackartists@gmail.com

#+DESCRIPTION: 
#+KEYWORDS: react-native
#+LANGUAGE:  en
#+OPTIONS:   num:t toc:nil ::t |:t ^:{} -:t f:t *:t <:t
#+OPTIONS:   tex:t d:nil todo:t pri:nil tags:nil
#+OPTIONS:   timestamp:t

# started this on 2020-03-09 Mon

# this allows defining headlines to be exported/not be exported
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport

# By default I do not want that source code blocks are evaluated on export. Usually
# I want to evaluate them interactively and retain the original results.
#+PROPERTY: header-args :eval never-export
#+startup: beamer
#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [t,10pt]
#+LaTeX_CLASS_OPTIONS: [aspectratio=169]

#+COLUMNS: %20ITEM %13BEAMER_env(Env) %6BEAMER_envargs(Args) %4BEAMER_col(Col) %7BEAMER_extra(Extra)

#+OPTIONS: H:3
#+BEAMER_THEME: Darmstadt
#+BEAMER_OUTER_THEME: miniframes [subsection=false]

#+BEAMER_HEADER: \usepackage[utf8]{inputenc}
#+BEAMER_HEADER: \usepackage{kotex}
#+BEAMER_HEADER: \usepackage{rotating}
#+BEAMER_HEADER: \usepackage{graphicx}
#+BEAMER_HEADER: \usepackage{amssymb,amsmath}
#+BEAMER_HEADER: \usepackage{amsthm}
#+BEAMER_HEADER: \usepackage{algorithmic}
#+BEAMER_HEADER: \usepackage[ruled,linesnumbered]{algorithm2e}
#+BEAMER_HEADER: \usepackage{listings}
#+BEAMER_HEADER: \usepackage[titletoc]{appendix}
#+BEAMER_HEADER: \usepackage{rotating}
#+BEAMER_HEADER: \usepackage{multirow}
#+BEAMER_HEADER: \usepackage{array}
#+BEAMER_HEADER: \usepackage{supertabular}
#+BEAMER_HEADER: \usepackage{dcolumn}
#+BEAMER_HEADER: \usepackage{adjustbox}
#+BEAMER_HEADER: \usepackage{epsfig}
#+BEAMER_HEADER: \usepackage{subfigure}
#+BEAMER_HEADER: \usepackage{acronym}
#+BEAMER_HEADER: \usepackage{url}
#+BEAMER_HEADER: \usepackage{graphicx}
#+BEAMER_HEADER: \usepackage{mathtools}
#+BEAMER_HEADER: \usepackage{longtable}
#+BEAMER_HEADER: \usepackage[acronym]{glossaries}
#+BEAMER_HEADER: \usepackage[font=small,skip=0pt]{caption}
#+BEAMER_HEADER: \usepackage{xcolor}
#+BEAMER_HEADER: \usepackage{color}
#+BEAMER_HEADER: \usepackage{colortbl}
#+BEAMER_HEADER: \usepackage{tikz}

#+BEAMER_HEADER: \AtBeginSection[]{
#+BEAMER_HEADER: \begin{frame}<beamer>\frametitle{Table of Contents}\begin{columns}[t]
#+BEAMER_HEADER: \begin{column}{.5\textwidth}\tableofcontents[currentsection,sections={1-3}]\end{column}
#+BEAMER_HEADER: \begin{column}{.5\textwidth}\tableofcontents[currentsection,sections={4-7}]\end{column}
#+BEAMER_HEADER: \end{columns}\end{frame}
#+BEAMER_HEADER: \subsection{}
#+BEAMER_HEADER: }
#+BEAMER_HEADER: \hypersetup{colorlinks=true, linkcolor=blue}
#+BEAMER: \setbeamercovered{transparent=30}
#+BEAMER_HEADER: \usepackage{blindtext}
#+BEAMER_HEADER: \input{../common/abb}
#+BEAMER_HEADER: \input{../common/options}

* React-Native and Android Setup

** React-Native Setup

*** Android Setup
 - Downloading [[https://adoptopenjdk.net/][AdoptOpenJDK]] version 8
 - Downloading [[https://dl.google.com/android/repository/commandlinetools-linux-6200805_latest.zip][Android SDK]]
 - Installing Android SDK into the PC
 #+BEGIN_SRC sh 
     unzip commandlinetools-linux-6200805_latest.zip
     cd tools
     export ANDROID_HOME="path-to-install-sdk"
     bin/sdkmanager --sdk_root=$ANDROID_HOME "tools"
     export PATH="$ANDROID_HOME/tools/bin:$ANDROID_HOME/tools:$ANDROID_HOME/emulator:$ANDROID_HOME/platform-tools:$PATH"
     mkdir ~/.android
     touch ~/.android/repositories.cfg
     sdkmanager "build-tools;28.0.3" "platforms;android-28"
 #+END_SRC
 - Installing AVD targets and running an emulator
 #+BEGIN_SRC sh
   sdkmanager "system-images;android-28;google_apis;x86_64" "system-images;android-28;google_apis;x86"
   avdmanager create avd --package "system-images;android-28;google_apis;x86_64" --name android-28
   avdmanager list avd
   emulator @android-28
 #+END_SRC

*** Installing react-native
- Installing ~react-native~
#+BEGIN_SRC sh
npm i -g react-native  
#+END_SRC
- Installing ~watchman~ for monitoring files chages
#+BEGIN_SRC sh
  sudo pacman -S watchman ## for Arch linux
  brew install watchman ## for Mac OS X

  ## General linux from source
  git clone https://github.com/facebook/watchman.git -b v4.9.0 --depth 1
  cd watchman 
  ./autogen.sh
  ./configure
  make
  sudo make install
#+END_SRC
- Initializing a project and building it
#+BEGIN_SRC sh
npx react-native init proj
cd proj/android
sudo pacman -S gradle ## brew install gradle
gralde build
#+END_SRC

*** Running an app on emulator
- We have to install an apk file into an emulator.
#+BEAMER: \vfill

#+BEGIN_SRC shell
  adb install path-to-apk/app.apk
#+END_SRC


* Android Native Modules

** Toast Module

*** Toast basic module
- Sometimes an app needs access to a platform API that React Native doesn't have a corresponding module for yet.
  - Native modules are usually distributed as npm packages
  - To get the basic scaffolding make sure to read [[https://reactnative.dev/docs/native-modules-setup][Native Modules Setup]]  guide first.

- Three steps
  - We start by creating a native module. 
  - Implement some override features: ~getName~, ~getConstants~ (opt).
  - To expose a method to JavaScript a Java method must be annotated using ~@ReactMethod~

*** A native module
- Creating a native module and override.
  - ~getName~ is mandatory for ~ReactContextBaseJavaModule~.
  - ~getConstants~ is optional override method.

#+BEGIN_SRC java
  public class ToastModule extends ReactContextBaseJavaModule {
      private static ReactApplicationContext reactContext;
      private static final String DURATION_SHORT_KEY = "SHORT";
      private static final String DURATION_LONG_KEY = "LONG";

      ToastModule(ReactApplicationContext context) {
          super(context);
          reactContext = context;
      }

      @Override
      public String getName() {
          return "ToastExample";
      }

      @Override
      public Map<String, Object> getConstants() {
          final Map<String, Object> constants = new HashMap<>();
          constants.put(DURATION_SHORT_KEY, Toast.LENGTH_SHORT);
          constants.put(DURATION_LONG_KEY, Toast.LENGTH_LONG);
          return constants;
      }

      @ReactMethod
      public void show(String message, int duration) {
          Toast.makeText(getReactApplicationContext(), message, duration).show();
      }
  }
#+END_SRC


*** Callbacks

*** Promieses

*** Threading

** Argument Types

*** Argument types

** Register the Module

*** Register the Module

** Sending Events

*** Events to JavaScript


* Useful Tips

** Platform Specific Code

*** Platform module
- When building a cross-platform app, *you'll want to re-use as much code as possible*.
  - For example you may want to implement separate visual components for Android and iOS.

- React Native provides two ways to organize your code and separate it by platform:

  - Using the Platform module.

  - Using platform-specific file extensions.


*** Platform module (platform.select)
- ~Platform.OS~ returns the value for the platform you are currently running on.
  - ~Platform.OS~ will be ~ios~ when running on iOS and ~android~ when running on Android.

**** Platform.OS                                                      :BMCOL:
     :PROPERTIES:
     :BEAMER_col: 0.5
     :END:

#+BEGIN_SRC js
  import {Platform, StyleSheet} from 'react-native';

  const styles = StyleSheet.create({
      height: Platform.OS === 'ios' ? 200 : 100,
  });
#+END_SRC

#+BEGIN_SRC js
  const Component = Platform.select({
      ios: () => require('ComponentIOS'),
      android: () => require('ComponentAndroid'),
  })();

      <Component />;
#+END_SRC


**** Platform.select                                                  :BMCOL:
     :PROPERTIES:
     :BEAMER_col: 0.5
     :END:
#+BEGIN_SRC js
  import {Platform, StyleSheet} from 'react-native';

  const styles = StyleSheet.create({
      container: {
          flex: 1,
          ...Platform.select({
              ios: {
                  backgroundColor: 'red',
              },
              android: {
                  backgroundColor: 'blue',
              },
          }),
      },
  });
#+END_SRC

***  Detecting the version
- ~Platform.Version~ can also be used to detect the version.
  - Android platform version is a google API version.
  - iOS version is a OS version such as *10.3*

**** the Android version                                              :BMCOL:
     :PROPERTIES:
     :BEAMER_col: 0.5
     :END:
#+BEGIN_SRC js
  import {Platform} from 'react-native';

  if (Platform.Version === 25) {
      console.log('Running on Nougat!');
  }
#+END_SRC

**** the iOS version                                                  :BMCOL:
     :PROPERTIES:
     :BEAMER_col: 0.5
     :END:
#+BEGIN_SRC js
  import {Platform} from 'react-native';

  const majorVersionIOS = parseInt(Platform.Version, 10);
  if (majorVersionIOS <= 9) {
      console.log('Work around a change in behavior');
  }  
#+END_SRC

*** Platform-specific extension
**** Platform-specific extension                                      :BMCOL:
     :PROPERTIES:
     :BEAMER_col: 0.5
     :END:
- When your platform-specific code is more complex, 
  - you should consider splitting the code out into separate files. 
  - React Native will detect when a file has a .ios. or .android. extension

#+BEAMER_HEADER: \vfill

#+BEGIN_SRC shell
  BigButton.ios.js
  BigButton.android.js
#+END_SRC

#+BEGIN_SRC js
  import BigButton from './BigButton';
#+END_SRC

**** Native-specific extensions                                       :BMCOL:
     :PROPERTIES:
     :BEAMER_col: 0.5
     :END:
- You can also use the .native.js extension when a module needs to be shared between NodeJS/Web and React Native
  - It has no Android/iOS differences.
  - The React Native bundler for both Android and iOS (Metro)

#+BEAMER_HEADER: \vfill

#+BEGIN_SRC shell
  Container.js
  Container.native.js
#+END_SRC

#+BEGIN_SRC js
  import Container from './Container';
#+END_SRC


** Navigating Between Screens

*** React navigation
- The community solution to navigation is a standalone library 

#+BEGIN_SRC shell
  npm install @react-navigation/native @react-navigation/stack
#+END_SRC

**** For Expo project                                                 :BMCOL:
     :PROPERTIES:
     :BEAMER_col: 0.5
     :END:
- Installing ~Expo~ packages.
#+BEGIN_SRC shell
  expo install react-native-reanimated react-native-gesture-handler react-native-screens react-native-safe-area-context @react-native-community/masked-view
#+END_SRC


**** For bare project                                                 :BMCOL:
     :PROPERTIES:
     :BEAMER_col: 0.5
     :END:
- Installing ~npm~ packages.
#+BEGIN_SRC shell
  npm install react-native-reanimated react-native-gesture-handler react-native-screens react-native-safe-area-context @react-native-community/masked-view
#+END_SRC

- Installing ~cocoapod~.
#+BEGIN_SRC shell
cd ios
pod install
cd ..
#+END_SRC


*** Usage
- There are 2 screens (Home and Profile) defined using the Stack.Screen component.

#+BEAMER: \vfill

#+BEGIN_SRC js
  import * as React from 'react';
  import {NavigationContainer} from '@react-navigation/native';
  import {createStackNavigator} from '@react-navigation/stack';
  const Stack = createStackNavigator();

  function MyStack() {
    return (
        <NavigationContainer>
        <Stack.Navigator>
        <Stack.Screen name="Home" component={Home} options={{title: 'Welcome'}} />
        <Stack.Screen name="Profile" component={Profile} />
        </Stack.Navigator>
        </NavigationContainer>
    );
  }
#+END_SRC

*** HomeScreen Implementation
- Each screen takes a component prop that is a React component.
  - The views in the stack navigator use native components and the Animated library to deliver 60fps animations

#+BEAMER: \vfill

#+BEGIN_SRC js
  function HomeScreen({navigation}) {
    return (
        <Button
      title="Go to Jane's profile"
      onPress={() => navigation.navigate('Profile', {name: 'Jane'})}
        />
    );
  }
#+END_SRC
